### ISSUE TITLE
IINA stopped working with OCLP 0.2.1/0.2.2

### ISSUE THREAD

**Issue by tsialex** [dortania/OpenCore-Legacy-Patcher#329]
I've noticed that IINA stopped opening videos with OCLP 0.2.1 installed. It's a MacBookPro8,1 11.4 (20F71) and IINA was working fine before rebooting to OCLP 0.2.1. 

**Edit: still fails with 0.2.2**

This is the system log:

```
Jun 23 15:10:37 MacBookPro8,1 com.apple.xpc.launchd[1] (application.com.colliderli.iina.12885451846.12885451851[371]): Service exited with abnormal code: 1
Jun 23 15:10:52 MacBookPro8,1 com.apple.xpc.launchd[1]: Coalition Cache Hit: app<application.com.colliderli.iina.12885451846.12885451851(501)> [408]
Jun 23 15:10:59 MacBookPro8,1 com.apple.xpc.launchd[1] (application.com.colliderli.iina.12885451846.12885451851[683]): Service exited with abnormal code: 1
Jun 23 15:12:40 MacBookPro8,1 com.apple.xpc.launchd[1]: Coalition Cache Hit: app<application.com.colliderli.iina.12885451846.12885451851(501)> [408]
Jun 23 15:12:53 MacBookPro8,1 com.apple.xpc.launchd[1] (application.com.colliderli.iina.12885451846.12885451851[706]): Service exited with abnormal code: 1
```

![Screen Shot 2021-06-23 at 15 20 43](https://user-images.githubusercontent.com/51399444/123148446-9fd83000-d436-11eb-8d5d-d550e5f4544f.png)

**Comment by khronokernel** [comment]
A MacBook8,1 natively supports Big Sur, confused why you would run OpenCore on this machine. Is this a typo?

**Comment by tsialex** [comment]
Sorry, MacBookPro8,1. 

Same problem with 0.2.2 too, just tested the nightly.

**Comment by khronokernel** [comment]
And you're certain 0.1.9 does not have this issue? Please run both versions and upload the builds generated

**Comment by tsialex** [comment]
> And you're certain 0.1.9 does not have this issue? 
Yes, I was watching a video just before upgrading to 0.2.1/0.2.2 

>Please run both versions and upload the builds generated
Done, thx.
[MacBookPro81.0.1.9 - 2021-06-23.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6704380/MacBookPro81.0.1.9.-.2021-06-23.zip)
[MacBookPro81.0.2.1 - 2021-06-23.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6704382/MacBookPro81.0.2.1.-.2021-06-23.zip)

**Comment by khronokernel** [comment]
What country are you located in? Seems the issue may related to country code

Try booting a native OS without OpenCore and build again, it should pull the correct country code

**Comment by tsialex** [comment]
> What country are you located in? Seems the issue may related to country code

Brazil.

**Comment by tsialex** [comment]
> Try booting a native OS without OpenCore and build again, it should pull the correct country code

Before looking for my High Sierra external disk, I've tried installing 0.1.9 from 11.4 and the issue persists.

**Comment by khronokernel** [comment]
Are you certain the issue is not IINA updated itself then? If 0.1.9 doesn't work either, there seems to be another variable that's the issue that's not OpenCore

Feel free to comment further on your findings and potential fixes but this is out of scope for us

**Comment by tsialex** [comment]
> Are you certain the issue is not IINA updated itself then?

Yes and I confirmed the issue reinstalling the same iina installer I've downloaded Monday when I did this 11.4 install from scratch.


> If 0.1.9 doesn't work either, there seems to be another variable that's the issue that's not OpenCore
I've installed my High Sierra disk back to the MBP and built 0.1.9 again, booted from it, installed post-patches - same issue with iina.  

This is weird, I'm gonna nuke my High Sierra disk and clean install 11.4 to confirm iina running with 0.1.9. Any tests/log that I need to save?

**Comment by tsialex** [comment]
So, did some tests:

11.4 + OCLP 0.1.9  + 0.1.9 Post-Install Volume Patch = IINA works fine
![Screen Shot 2021-06-23 at 20 28 28](https://user-images.githubusercontent.com/51399444/123182679-4f78c680-d466-11eb-9527-748ce1bfe579.png)

11.4 + OCLP 0.2.2 + 0.1.9 Post-Install Volume Patch = IINA works fine
![Screen Shot 2021-06-23 at 20 35 01](https://user-images.githubusercontent.com/51399444/123182736-6f0fef00-d466-11eb-97e5-a0ffac321576.png)

11.4 + )CLP 0.2.2 + 0.2.2 Post-Install Volume Patch = IINA crashes when opening the video
![Screen Shot 2021-06-23 at 20 58 31](https://user-images.githubusercontent.com/51399444/123182764-7f27ce80-d466-11eb-923a-2f255d3be5d7.png)

**Comment by tsialex** [comment]
Confirmed  @khronokernel, clean install of 11.4 + OCLP 0.2.2 + 0.2.2 Post-Install Volume Patch don't work, OpenGL function pointer failure.
![Screen Shot 2021-06-23 at 22 36 47](https://user-images.githubusercontent.com/51399444/123189401-252e0580-d474-11eb-9466-a707153fc08d.png)

**Comment by khronokernel** [comment]
Looking at the patch set between 0.2.1 and 0.1.9 are identical so not entirely sure the issue. When you run the 0.2.1 Root Patcher, can you send the checksum it lists from the download?

**Comment by tsialex** [comment]
> Looking at the patch set between 0.2.1 and 0.1.9 are identical so not entirely sure the issue. When you run the 0.2.1 Root Patcher, can you send the checksum it lists from the download?

Checksum: 93dee304567a8efd22665e8b60a244137645e64133a785b388baa4ab95d255fd

**Comment by khronokernel** [comment]
So comparing the checksum from running curl, it does seem to be broken:
3d021903a7dd986d6309a4275ac4dc9af5f59aae

I can also replicate and my OCLP checksum is identical when running 0.2.1:
```
- Checksum: 93dee304567a8efd22665e8b60a244137645e64133a785b388baa4ab95d255fd
```

So it seems something is getting corrupt during the download. Will need to investigate further

**Comment by khronokernel** [comment]
Typo, shamus is correct:
```
3d021903a7dd986d6309a4275ac4dc9af5f59aae  ./Apple.zip
```
So files are not corrupt

**Comment by khronokernel** [comment]
Found the culprit, symlinks are broken:

<img width="1798" alt="Screen Shot 2021-06-23 at 8 27 47 PM" src="https://user-images.githubusercontent.com/48863253/123193387-f444d500-d461-11eb-829d-98e538012996.png">

This is due to us using Github Actions' servers and running just `zip` to compress the binaries without preserving symlinks. We added `--symlinks` to the build script so should be resolved now. Please verify the latest commit works:

https://github.com/dortania/OpenCore-Legacy-Patcher/suites/3072362435/artifacts/70015427

**Comment by tsialex** [comment]
Still not working when updating the previous not working 11.4 + 0.2.2 install.

**Comment by khronokernel** [comment]
Verify files were correctly updated under:

* System/Library/Frameworks/OpenGL.framework
* System/Library/PrivateFrameworks/GPUSupport.framework

Those 2 frameworks rely on symlinks

If you're unsure, send me a screenshot of both folders expanded in list view (Cmd + 2)

**Comment by tsialex** [comment]
Thx for looking at this issue.

![Screen Shot 2021-06-24 at 19 37 56](https://user-images.githubusercontent.com/51399444/123341168-e48dc500-d523-11eb-9274-4ea57fb22105.png)

**Comment by khronokernel** [comment]
Yeah seems symlinks are still broken, seems rsync couldn't overwrite for whatever reason. I believe the best course of action is to simply manually delete and install instead of attempting for rsync to overwrite. This will only be for your setup (and if someone else reports issues) as I don't believe forceful deletion is a great idea for the overall user base (can bring in edge cases where we want to retain certain files missing in the repository or requires additional binaries like Skylight patch set)

Will send a build later today that does this, or may be this weekend depending if I got caught up in something. Appreciate the patients regarding this

**Comment by tsialex** [comment]
Just did a clean install with nightly 0.2.3 + 0.2.3 Post-Install Volume Patch and same problem:
![Screen Shot 2021-06-27 at 15 15 06](https://user-images.githubusercontent.com/51399444/123555365-b692c580-d75b-11eb-84e5-91f65aab2d8b.png)

**Comment by khronokernel** [comment]
Please verify integrity of symlinks as previously done:

* System/Library/Frameworks/OpenGL.framework
* System/Library/PrivateFrameworks/GPUSupport.framework

**Comment by tsialex** [comment]
Clean install of 11.4 + nightly 0.2.3 + 0.2.3 Post-Install Volume Patch (IINA don't work):
![023+023](https://user-images.githubusercontent.com/51399444/123556588-65d29b00-d762-11eb-9989-183689f1bf32.png)
Clean install of 11.4 + nightly 0.2.3 + 0.1.9 Post-Install Volume Patch (IINA do work):
![023+019 a](https://user-images.githubusercontent.com/51399444/123556600-76831100-d762-11eb-9bf4-dde4629c5e92.png)
![023+019 b](https://user-images.githubusercontent.com/51399444/123556602-78e56b00-d762-11eb-852c-fec7f6310f4b.png)

**Comment by khronokernel** [comment]
https://github.com/dortania/OpenCore-Legacy-Patcher/suites/3099354221/artifacts/70836222

Verify this build please

**Comment by tsialex** [comment]
`Building Configuration on model: MacBookPro8,1
Created build folder

- Adding OpenCore v0.7.0 RELEASE
- Adding config.plist for OpenCore
- Adding Lilu.kext 1.5.4
- Adding WhateverGreen.kext 1.5.1
- Adding NightShiftEnabler.kext 1.1.0
- Adding SMC-Spoof.kext 1.0.0
- Adding CPUFriend.kext 1.2.4
- Adding CatalinaBCM5701Ethernet.kext 1.0.1
- Adding AppleALC.kext 1.6.2
- No 3rd Party NVMe drives found
- Found Wireless Device 14E4:4331
- Adding AirportBrcmFixup.kext 2.1.3
- Found ARPT device at PciRoot(0x0)/Pci(0x1c,0x1)/Pci(0x0,0x0)
- Applying fake ID for WiFi, setting Country Code: US
Traceback (most recent call last):
  File "OpenCore-Patcher.command", line 296, in <module>
  File "OpenCore-Patcher.command", line 290, in main_menu
  File "Utilities.py", line 246, in start
  File "OpenCore-Patcher.command", line 76, in build_opencore
  File "Build.py", line 872, in build_opencore
  File "Build.py", line 294, in build_efi
  File "Build.py", line 268, in wifi_fake_id
TypeError: unsupported operand type(s) for +=: 'dict' and 'dict'
[1291] Failed to execute script OpenCore-Patcher
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.`

**Comment by khronokernel** [comment]
Please test new root patches, not OpenCore building

**Comment by tsialex** [comment]
Seems to be working now, thx! =)

What was the real issue?

**Comment by khronokernel** [comment]
Great to hear! The issue was 2 parts:

* build server not preserving symlinks
* rsync in the patcher not preserving 

The latter is what I just fixed in master so should be good now. Appreciate the patience regarding all this. Also the wifi build issue you noticed earlier is resolved as well
